### PR TITLE
New Nationality and residency section

### PR DESCRIPTION
**Pull request by frankieroberto**
This is a design for a new section called "Nationality and residency'

This contains:

* Existing nationality question (moved from 'Personal details')
* Existing immigration status question (moved from 'Personal details')
* A new question about living continuously in [list of countries] in the 3 years before the course starts

These questions are all asked to help providers determine:

* whether the candidate has the right to study or work in the UK
* whether the candidate is eligible for 'home fee status' and student finance

The answers should not be used by providers to determine suitability for the course.

🗂️ [Trello card](https://trello.com/c/4SRH7s19/4598-home-fee-status-questions)
➡️ [Design history entry](https://bat-design-history.netlify.app/apply-for-teacher-training/home-fee-status/)

## Relevant links

* [Student finance eligibility on GOV.UK](https://www.gov.uk/student-finance/who-qualifies)
* [Trello card](https://trello.com/c/NkSrSUL3/4485-home-fee-status-questions-user-journey-map-next-steps)
* [Flow diagram](https://lucid.app/lucidspark/f40c9430-c8d9-47f5-92f8-950d2469fc0e/edit#)

### CODE REVIEW

**Comment by frankieroberto** [comment]
Screenshots of work in progress:

### New section in application overview

Screenshot 2022-03-31 at 16 09 57

### Updated immigration status question
immigration-status

### Where you’ve been living (British citizens)
where-youve-been-living

### Where you’ve been living (Irish citizen) – showing revealed question for ’No’
living-details

### Where you’ve been living (EU settled status)
living-eu

### Section review page
nationality-review

**Comment by EmmaFrith** [comment]
I'm not sure about this. 

I feel the way these questions are framed gives too much weight to a section of the application form that we actually want candidates to whiz through. 

Most people should be able to select 'yes' very quickly to the question 'Will you have been living in [x countries] for 3 years by the time the course starts?'. 

I don't think we should be listing every country in the EU or EEA etc - I think it's too much. Most people will know if they're in an EU country etc. 

Can we simplify this? For example:

Screenshot 2022-04-04 at 21 12 32

**Comment by frankieroberto** [comment]
@EmmaFrith I wasn’t sure if we should list every country in the EU and EEA either, but I wasn’t sure that everyone would always know which countries they were (particularly the EEA)? Listing the Isle of Man and Channel Islands (not to mention the Falkland Islands and Gibraltar) also seems to give them a lot a weight given how few candidates we likely get from there? Tricky!

I’m up for trying a shorter version without the list. I think the hint text in your screenshot is likely too long for accessibility reasons though, so we’d still end up needing a separate h1 and question text. This does let us use paragraph breaks in the guidance text though, and have it appear black not dark grey.

**Comment by EmmaFrith** [comment]
Thanks @frankieroberto. 

Excuse the poor prototyping skills here... I don't think we necessarily need the separate H1 and question text. For example: 

Screenshot 2022-04-05 at 11 34 45

I'm also trying options with the existing structure, e.g.:

Screenshot 2022-04-05 at 11 45 48

It would be good to try both but my prototyping skills are lacking!

**Comment by frankieroberto** [comment]
Updated screenshots of our (final?) design...  We decided to split up the "Where you've been living" question so that the first question, covering the majority of instances, only asks about the UK and Ireland. If answering No, a follow-up question is shown which lists countries and areas as checkboxes. If "Somewhere else" is selected, a final question is shown asking for details.

application

nationality

right-to-work

immigration-status

living

living-more

living-details

review

**Review by EmmaFrith — CHANGES_REQUESTED** [review]
We still need to do that routing thing, where candidates with a non-EU nationality are *not* directed through the residency questions if they select EU settled or pre-settled status. 
(Only EU nationals with EU settled or pre-settled status can be eligible for home fees - non EU nationals with EU settled or pre-settled status won't be eligible for home fees, so no point in asking about their residency)

**Comment by frankieroberto** [comment]
Closing this, as we decided not to go ahead with this work for now. It has been written up as a design elsewhere: [Helping providers assess a candidate’s fee status](https://bat-design-history.netlify.app/apply-for-teacher-training/home-fee-status/)

**Pull request closed without merging**
