### PR TITLE
Upgrade to Node 15

### PR DESCRIPTION
**Pull request by frankieroberto**
This is the only version that supports newer Macs (with the M1 ARM chip), it seems...

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Has somebody bought themselves a new Mac? 😮

**Comment by paulrobertlloyd** [comment]
Need to update `.nvmrc` too.

**Comment by frankieroberto** [comment]
@paulrobertlloyd the battery on my old one is dying... 😢  It's done 7 years good service though.

**Comment by paulrobertlloyd** [comment]
Mine’s of a similar vintage… a bit like Trigger’s broom though with a new screen, battery and a few other bits. I’m holding out for the new M1(X?) 16" though…

**Review by paulrobertlloyd — APPROVED** [review]

**Pull request merged**
